### PR TITLE
Updating framerate management

### PR DESCRIPTION
**Pull request by havetc**
I thinks that it should solve issue #15 , on my system I have no more-slow mo videos (for big resolution and high fps source) or increased speed ones (for small videos with low source fps  and displayed in a tiny window).

Now the lag is registered globally (and not only the delta time to the frame before), which allows to skip frames or to sleep more precisely, if lags accumulate slowly

Tested on a 120fps 1080p video, it skipped a lot of frames but the video speed was accurate. On small SD videos, it was displaying the right framerate, without skip and without going too fast.

### CODE REVIEW

**Comment by PaulleDemon** [comment]
Hi, thank you for creating the pull request. I am busy this month. I'll try to look into this as soon as I am free. Thank you.

**Comment by PaulleDemon** [comment]
Hi @havetc sorry for the late reply, I just got freed from work. I tested with a few files but it lags a little or sometimes feels glitochy, maybe because it's skipping too many frames. Would you be able to fix that and let me know? I'll test it again and go for the merge

**Comment by PaulleDemon** [comment]
I'll close this pull request and merge this with pull #34 since both are similar. We'll continue there.

**Comment by havetc** [comment]
Do you want me to add this to #34? I'm not sure what you want me to do. 
Otherwise I know that on big files it can feels glitchy: this is not unexpected, as indeed on my system, a 4k60 video current implementation goes as slow as about 9 fps (without #34, which about triple that ), so indeed it plays less than 20% of the frames and skips the rest.

**Pull request closed without merging**
